version: "2"
services:

  alfresco:
    container_name: alfresco-vm
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    mem_limit: 6192G
    ports:
      - "21:21"
      - "8080:8080"
    volumes:
      - data:/alfresco-recovery

#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://192.168.0.42:123"

volumes:
  data:
    driver: local
