version: "2"
services:

  alfresco:
    container_name: alfresco-vm
    build: build
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
      nproc: 65535
    stdin_open: true
