version: "2"
services:

  alfresco:
    container_name: alfresco-vm
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - HEAPSIZE=1192M
      - MEMSIZE=4096M
    ports:
      - "21:21"
      - "8100:8100"
      - "8080:8080"
      - "56000-56009:56000-56009"
    volumes:
      - data:/alfresco-recovery
    tty: true

volumes:
  data:
    driver: local
